### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by alfasst** [AnthonyMRios/pyclausie#2]
When running `triples = cl.extract_triples(sents)`, Python throws a permission error as: 

```
File "C:\ProgramData\Anaconda3\lib\site-packages\pyclausie-0.1-py3.6.egg\pyclausie\SubprocessBackend.py", line 72, in extract_triples
    os.remove(input_file.name)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ADMIN123\\AppData\\Local\\Temp\\tmpuim6i8ma'
```

Please solve it and update.

**Comment by AnthonyMRios** [comment]
Hi altfasst,

My code does not run on Windows because I use the NamedTempFile method. If you use on Linux or Mac, then everything should work.

**Comment by andreacortis** [comment]
Hi, this was breaking my head ... you should have a very visible disclaimer on the readme. Closing this issue is not a solution to the issue!
